kind: BearerAuth
apiVersion: github.com/v1alpha1
metadata:
  name: github-bearer
spec:
  deletionPolicy: Orphan 
  token: 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