kind: ServiceEndpoint
apiVersion: azure.devops.com/v1alpha1
metadata:
  name: se-1
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
spec:
  deletionPolicy: Delete
  authenticationRefs:
    basicAuthRef: basicauth-azure
  # description: created by Krateo
  project: pipelineProj
  data:
    environment: AzureCloud
    scopeLevel: Subscription
    subscriptionId: 1272a66f-e2e8-4e88-ab43-487409186c3f
    subscriptionName: Microsoft Azure Sponsorship
    creationMode: Manual
  name: se-14-auto
  type: AzureRM
  url: https://management.azure.com/
  authorization:
    parameters:
      tenantid: 1272a66f-e2e8-4e88-ab43-487409186c3f
      serviceprincipalId: 1272a66f-e2e8-4e88-ab43-487409186c3f
      authenticationType: spnKey
      serviceprincipalKey: somePassword
    scheme: ServicePrincipal
  isShared: true
  serviceEndpointProjectReferences:
    - projectReference:
        name: pipelineProj
        id: 915d9571-f027-40a6-ae76-5108c5f90e18
      name: se-14-auto
  #   - projectReference:
  #       name: testShare
  #       id: f5d938a5-4816-4a5a-894b-38d5bcf40738
  #     name: testShare-endpoint-auto-16
  organization: matteogastaldello-org
  api-version: 7.2-preview.4

  